### PR TITLE
Meaningful exception message on invalid XML content

### LINKED ISSUE #58: CellXocument throws incomprehensible Exception when XML is broken
### Expected Behavior

Human readable exception message with hint to the problem.

### Actual Behavior

The Exception is thrown:
```
System.Xml.XmlException
'.', hexidezimaler Wert 0x00, ist ein ungültiges Zeichen. Zeile 1, Position 1.
```

### Mention any other details that might be useful

Exception thrown when accessing a XML file with some zero bytes as content.

### PR DESCRIPTION
**Pull request by aveXcaesar**
### Please check if the PR fulfills these requirements
- [x] I made sure that my code builds
- [x] I merged the master into this branch before pushing
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### What is the current behavior? (You can also link to an open issue here)

closes #58 

### What is the new behavior?

CellXocument delivers meaningful exception when XML is invalid.

### Does this PR introduce a breaking change? (check one with "x")
- [ ] Yes
- [x] No

###  Other information

### CODE REVIEW

File: src/Xive/Xocument/CellXocument.cs [hunk 1]
```diff
@@ -93,13 +93,24 @@ public sealed class CellXocument : XocumentEnvelope
...
+                                                        new InputOf(content),
+                                                        encoding
+                                                    ).AsString()
+                                                );
+                                        }
+                                        catch (XmlException ex)
+                                        {
+                                            throw
+                                                new ApplicationException(
+                                                    $"Cannot make XML from cell with name '{cell.Name()}' and content: '{new TextOf(new InputOf(content), encoding).AsString()}'",
```
Comment (koeeenig) [inline src/Xive/Xocument/CellXocument.cs]:
```suggestion
                                                    $"Cannot parse content as XML from cell '{cell.Name()}'. Content: '{new TextOf(new InputOf(content), encoding).AsString()}'",
```
