### PR TITLE
Bug Textindex Remove nullref exception

### LINKED ISSUE #116: Bug _guts.xml does not work with filehive
### Expected Behavior

The _guts.xml works with the filehive
### Actual Behavior

The xmlInFiles tries to parse all files as a xml also the files that are no xml
### Mention any other details that might be useful

The XmlInFiles tries to parse the catalog.cat as xml because the xmlInFiles.Knowledge() returns all data including files that are no xml.

The xmlInFiles need to save the files that are xml files like the XmlInRam. Otherwise we dont know if the file is last accessed via Xocument or via Cell

### LINKED ISSUE #117: Removing index from textindex occasionally throws nullreference exception
### Expected Behavior

no exception is thrown
### Actual Behavior

Occasionally a nullref is thrown in the parallel foreach

### PR DESCRIPTION
**Pull request by icaHWI**
### Please check if the PR fulfills these requirements
- [x] I made sure that my code builds
- [x] I merged the master into this branch before pushing
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### What is the current behavior? (You can also link to an open issue here)

closes #117 
closes #116 
### Does this PR introduce a breaking change? (check one with "x")
- [ ] Yes
- [ ] No

###  Other information

### CODE REVIEW

File: src/Xive/Props/Facets/EncodedProp.cs [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+
+namespace Xive.Props
+{
+    /// <summary>
+    /// Replaces ':' and ',' with '&#42' and '&#43'
+    /// </summary>
+    public sealed class EncodedProp : IScalar<string>
+    {
+        private readonly string origin;
+        private const string replaceColon = "&#42";
```
Comment (Meerownymous) [inline src/Xive/Props/Facets/EncodedProp.cs:36]: I think we should use a more robust approach for encoding.
When you encode a comma to &#42, it might occur that someone sets a property value to "&#42" and this breaks the xive in another way.

The robust way would be to encode ALL special characters.

You can either build an own encoding, or use an existing one. An existing one could be 
https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlconvert.encodename?view=netcore-3.1

Please check if it encodes all characters.

Alternative:
WebUtility.UrlEncode()
